name: First Workflow

on: workflow_dispatch

jobs:
  first-job:
    runs-on: ubuntu-latest
    steps:
      - name: Print greetings
        run: |
          echo "Hi!"
          echo "I am rezaul Karim"
      - name: Print goodbye
        run: echo "Goodbye world!"
